name: Deploy Vite Site

on:
  push:
    branches: ["main"] # Vérifie que ta branche s'appelle bien main (et pas master)

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # C'est ici que Vite met les fichiers compilés

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4